language: minimal
os: linux
dist: xenial
group: stable
sudo: required

env:
  global:
    # https://developer.android.com/studio#downloads
    # SDK Tools, Revision 26.1.1
    - ANDROID_SDK_FILENAME=sdk-tools-linux-4333796.zip
    - ANDROID_PLATTFORM_SDK=28
    - ANDROID_BUILD_TOOLS=28.0.3

before_install:
  # install/upgrade OpenJDK8
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - java -version
  # print available java paths and only set JAVA_HOME if contains expected one
  - sudo update-alternatives --config java | grep -q '/usr/lib/jvvm/java-8-openjdk-amd64' && export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 | true
  # download Android SDK Tools
  - wget https://dl.google.com/android/repository/$ANDROID_SDK_FILENAME
  # create new /sdk folder in /home/travis dir
  - mkdir $HOME/sdk
  # unzip SDK Tools into sdk folder
  - unzip -q $ANDROID_SDK_FILENAME -d $HOME/sdk
  # add SDK Tools path variable
  - export PATH=$PATH:$HOME/sdk/tools/bin
  # set ANDROID_HOME path
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

install:
  # SDK Platform-Tools
  - yes | sdkmanager "platform-tools" >/dev/null
  # SDK Platform
  - yes | sdkmanager "platforms;android-$ANDROID_PLATTFORM_SDK" >/dev/null
  # SDK Build-Tools
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS" >/dev/null
  # Android Support Repository
  - yes | sdkmanager "extras;android;m2repository" >/dev/null
  #Google Repository
  - yes | sdkmanager "extras;google;m2repository" >/dev/null
  # list installed and available packages
  - sdkmanager --list

before_script:
  # set executable flag for gradle wrapper
  - chmod +x gradlew
  # create dir for gradle settings
  - mkdir -p $HOME/.gradle
  # disable gradle daemon for current user
  - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
  # set gradle log format to plain
  - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties

script:
  - ./gradlew assembleDebug
