language: minimal
os: linux
dist: xenial
group: stable
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    # SDK Tools Revision 26.1.1
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip
    # For Updates check https://developer.android.com/studio#downloads

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/

before_install:
  # check if OpenJDK8 is installed and install if missing
  - if ! dpkg -s openjdk-8-jdk >/dev/null 2>&1; then sudo apt-get update; sudo apt-get install openjdk-8-jdk; fi
  - java -version
  # print available java versions with their path (must contain java-8-openjdk-amd64)
  - sudo update-alternatives --config java
  # set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # download und unzip Android SDK Tools
  - wget https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  # set SDK Tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

install:
  # latest SDK Platform-Tools
  - yes | sdkmanager "platform-tools" >/dev/null
  # defined SDK Platform
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL" >/dev/null
  # defined SDK Build-Tools
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
  # list installed and available packages
  - sdkmanager --list

before_script:
  # set executable flag for gradle wrapper
  - chmod +x gradlew
  # create dir for gradle settings
  - mkdir -p $HOME/.gradle
  # disable gradle daemon for current user
  - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
  # set gradle log format to plain
  - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties

script:
  - ./gradlew assembleDebug

before_cache:
  - find $HOME/.gradle/caches/ -type f -name '*.lock'
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  # only cache last gradle version used by the wrapper
  # list content in wrapper/dist sorted by modification time and remove entries starting by the second entry
  - ls -d $HOME/.gradle/wrapper/dists/* -1t | tail -n +2 | xargs rm -rf