language: minimal
dist: xenial
sudo: required

env:
  global:
    - ANDROID_SDK_FILENAME=sdk-tools-linux-4333796.zip

before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - java -version
  - sudo update-alternatives --config java
  - wget https://dl.google.com/android/repository/$ANDROID_SDK_FILENAME
  - unzip $ANDROID_SDK_FILENAME