os: linux
dist: xenial
jdk: openjdk8

language: android
android:
  components:
     - tools
     - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - sudo apt-get install wget build-essential openjdk-8-jdk python cmake libssl-dev
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version