language: android
jdk: openjdk8
dist: trusty
group: stable

android:
  components:
    - tools
    - platform-tool
    - build-tools-28.0.3
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
