language: minimal
dist: xenial
sudo: required

env:
  global:
    - ANDROID_SDK_FILENAME=sdk-tools-linux-4333796.zip

before_install:
  - pwd
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - java -version
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - sudo update-alternatives --config java
  - wget https://dl.google.com/android/repository/$ANDROID_SDK_FILENAME
  - mkdir $HOME/sdk
  - unzip $ANDROID_SDK_FILENAME -d $HOME/sdk
  - ls
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - sdkmanager --list
