name: Android CI

on:
  push:
    branches:
    - develop
    - master

jobs:
  my-build:
    name: Build Debug
    runs-on: ubuntu-latest
    container: openjdk:11-jdk-slim

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build with Gradle
        run: ./gradlew assembleDebug